"""
================================================================================
PUCCH Format 0 - Multi-User ML Decoder
Configuration File
================================================================================

This file contains ALL configuration parameters for the Multi-User experiment.
It maps exactly to the data generated by the MATLAB multi-user script.

Novelty:
    Decoding a target user (m0=0) in the presence of intra-cell interference
    from other users multiplexed on the same PRB using different cyclic shifts.

Scenarios generated by MATLAB:
    1. '2users': Target user (m0=0) + 1 Interferer (m0=1)
    2. '3users': Target user (m0=0) + 2 Interferers (m0=1, m0=2)

================================================================================
"""

import os
import datetime


class ConfigMultiUser:
    """
    Central configuration class containing all parameters for the 
    Multi-User interference experiment.
    """

    # =========================================================================
    # SECTION 1: EXPERIMENT IDENTIFICATION
    # =========================================================================

    EXPERIMENT_NAME = "PUCCH_Format0_MultiUser_Decoder"
    EXPERIMENT_VERSION = "1.0"
    EXPERIMENT_TIMESTAMP = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    # =========================================================================
    # SECTION 2: RANDOM SEEDS FOR REPRODUCIBILITY
    # =========================================================================

    MASTER_SEED = 42
    NUMPY_SEED = 42
    TENSORFLOW_SEED = 42
    SKLEARN_SEED = 42

    # =========================================================================
    # SECTION 3: MULTI-USER SCENARIOS (Must match MATLAB output)
    # =========================================================================

    # Scenario names exactly as generated in MATLAB strings
    SCENARIOS = ['2users', '3users']

    # Target user index and shift
    TARGET_M0 = 0

    # =========================================================================
    # SECTION 4: DATA PARAMETERS
    # =========================================================================

    DATA_DIR = "./"

    # SNR configuration
    SNR_VALUES = [0, 5, 10, 15, 20]  # dB
    TRAIN_SNR = 10  # dB

    # Feature dimensions
    NUM_FEATURES = 24  # 12 real + 12 imaginary
    NUM_SUBCARRIERS = 12

    # Class configuration (Target User only)
    NUM_CLASSES = 4

    # Class definitions for the target user (m0=0)
    CLASS_LABELS = {
        0: "ACK=0, SR=0 (NACK, no SR)",
        1: "ACK=0, SR=1 (NACK, +SR)",
        2: "ACK=1, SR=0 (ACK, no SR)",
        3: "ACK=1, SR=1 (ACK, +SR)"
    }

    # Expected CSV Format
    EXPECTED_NUM_COLUMNS = 25  # 24 features + 1 label
    FEATURE_COLUMNS_REAL = [f"real_{i}" for i in range(1, 13)]
    FEATURE_COLUMNS_IMAG = [f"imag_{i}" for i in range(1, 13)]
    FEATURE_COLUMNS = FEATURE_COLUMNS_REAL + FEATURE_COLUMNS_IMAG
    LABEL_COLUMN = "label"

    # File naming pattern from MATLAB: pucch_f0_{scenario}_SNR_{snr}dB.csv
    FILE_PATTERN = "pucch_f0_{scenario}_SNR_{snr}dB.csv"

    # =========================================================================
    # SECTION 5: MATLAB GENERATION PARAMETERS (For Documentation)
    # =========================================================================

    MATLAB_SAMPLES_PER_SNR = 200000
    MATLAB_SAMPLES_PER_CLASS = 50000
    MATLAB_ALLOWED_SLOTS = [13, 14]
    MATLAB_SYMBOL_START = 13
    MATLAB_SYMBOL_COUNT = 1
    MATLAB_FREQUENCY_HOPPING = "neither"
    MATLAB_CHANNEL_MODEL = "TDL-C"
    MATLAB_DELAY_SPREAD = 300e-9
    MATLAB_MAX_DOPPLER = 100
    MATLAB_INDEPENDENT_CHANNELS_PER_USER = True
    MATLAB_NCELL_ID = 2
    MATLAB_SUBCARRIER_SPACING = 15
    MATLAB_NSIZE_GRID = 25
    MATLAB_NUM_TX_ANTENNAS = 1
    MATLAB_NUM_RX_ANTENNAS = 1

    # =========================================================================
    # SECTION 6: DATA SPLITTING
    # =========================================================================

    TRAIN_RATIO = 0.75
    VALIDATION_RATIO = 0.25
    STRATIFY_SPLIT = True

    # =========================================================================
    # SECTION 7: DATA PREPROCESSING
    # =========================================================================

    NORMALIZE_FEATURES = False
    NORMALIZATION_TYPE = "standard"

    # =========================================================================
    # SECTION 8: NEURAL NETWORK ARCHITECTURE
    # =========================================================================

    INPUT_SIZE = 24
    HIDDEN_LAYERS = [128, 128]
    HIDDEN_ACTIVATION = "relu"
    OUTPUT_SIZE = 4
    OUTPUT_ACTIVATION = "softmax"
    DROPOUT_RATE = 0.5
    USE_DROPOUT = True
    KERNEL_INITIALIZER = "glorot_uniform"

    # =========================================================================
    # SECTION 9: TRAINING PARAMETERS
    # =========================================================================

    NUM_EPOCHS = 200
    BATCH_SIZE = 256
    OPTIMIZER = "sgd"
    LEARNING_RATE = 1e-3
    MOMENTUM = 0.9
    USE_NESTEROV = False
    LOSS_FUNCTION = "categorical_crossentropy"

    # =========================================================================
    # SECTION 10: TRAINING CALLBACKS
    # =========================================================================

    USE_EARLY_STOPPING = True
    EARLY_STOPPING_MONITOR = "val_loss"
    EARLY_STOPPING_MODE = "min"
    EARLY_STOPPING_PATIENCE = 20
    EARLY_STOPPING_MIN_DELTA = 0.0001
    EARLY_STOPPING_RESTORE_BEST = True

    USE_MODEL_CHECKPOINT = True
    CHECKPOINT_MONITOR = "val_accuracy"
    CHECKPOINT_MODE = "max"
    CHECKPOINT_SAVE_BEST_ONLY = True

    USE_REDUCE_LR = True
    REDUCE_LR_MONITOR = "val_loss"
    REDUCE_LR_FACTOR = 0.5
    REDUCE_LR_PATIENCE = 10
    REDUCE_LR_MIN_LR = 1e-6

    # =========================================================================
    # SECTION 11: OUTPUT DIRECTORIES AND FILES
    # =========================================================================

    RESULTS_DIR = "./results_multiuser/"
    MODELS_DIR = "./models_multiuser/"
    PLOTS_DIR = "./plots_multiuser/"
    LOGS_DIR = "./logs_multiuser/"

    # Base filenames (Scenario name will be injected dynamically)
    SCALER_FILENAME = "feature_scaler_mu_{scenario}.pkl"
    TRAINING_HISTORY_FILENAME = "training_history_mu_{scenario}.csv"
    RESULTS_FILENAME = "results_summary_mu_{scenario}.csv"

    # =========================================================================
    # SECTION 12: VISUALIZATION SETTINGS
    # =========================================================================

    FIGURE_SIZE_SMALL = (8, 6)
    FIGURE_SIZE_MEDIUM = (10, 6)
    FIGURE_SIZE_LARGE = (12, 8)
    FIGURE_SIZE_WIDE = (14, 5)
    FIGURE_DPI = 150

    # =========================================================================
    # SECTION 13: UTILITY METHODS
    # =========================================================================

    @classmethod
    def create_directories(cls):
        """Create all output directories if they don't exist."""
        directories = [cls.RESULTS_DIR, cls.MODELS_DIR,
                       cls.PLOTS_DIR, cls.LOGS_DIR]
        for directory in directories:
            if directory and not os.path.exists(directory):
                os.makedirs(directory)
                print(f"Created directory: {directory}")

    @classmethod
    def get_data_filepath(cls, scenario: str, snr_db: int) -> str:
        """Get the full file path for a dataset based on scenario and SNR."""
        if scenario not in cls.SCENARIOS:
            raise ValueError(
                f"Scenario '{scenario}' is not valid. Choose from {cls.SCENARIOS}")
        filename = cls.FILE_PATTERN.format(scenario=scenario, snr=snr_db)
        return os.path.join(cls.DATA_DIR, filename)

    @classmethod
    def get_model_filepath(cls, scenario: str) -> str:
        """Get the full file path for saving/loading a model for a specific scenario."""
        filename = f"pucch_f0_multiuser_nn_{scenario}.h5"
        return os.path.join(cls.MODELS_DIR, filename)

    @classmethod
    def get_history_filepath(cls, scenario: str) -> str:
        """Get the full file path for saving training history."""
        filename = cls.TRAINING_HISTORY_FILENAME.format(scenario=scenario)
        return os.path.join(cls.LOGS_DIR, filename)

    @classmethod
    def get_results_filepath(cls, scenario: str) -> str:
        """Get the full file path for saving results CSV."""
        filename = cls.RESULTS_FILENAME.format(scenario=scenario)
        return os.path.join(cls.RESULTS_DIR, filename)

    @classmethod
    def validate_config(cls) -> bool:
        """Validate configuration parameters for consistency."""
        errors = []
        if cls.TRAIN_SNR not in cls.SNR_VALUES:
            errors.append(f"TRAIN_SNR ({cls.TRAIN_SNR}) not in SNR_VALUES")
        if abs(cls.TRAIN_RATIO + cls.VALIDATION_RATIO - 1.0) > 0.001:
            errors.append("TRAIN_RATIO + VALIDATION_RATIO should equal 1.0")
        if cls.INPUT_SIZE != cls.NUM_FEATURES:
            errors.append(
                f"INPUT_SIZE ({cls.INPUT_SIZE}) should equal NUM_FEATURES ({cls.NUM_FEATURES})")
        if cls.OUTPUT_SIZE != cls.NUM_CLASSES:
            errors.append(
                f"OUTPUT_SIZE ({cls.OUTPUT_SIZE}) should equal NUM_CLASSES ({cls.NUM_CLASSES})")

        if errors:
            print("\n" + "!" * 70)
            print("CONFIGURATION VALIDATION ERRORS")
            print("!" * 70)
            for error in errors:
                print(f"  - {error}")
            print("!" * 70 + "\n")
            return False
        return True

    @classmethod
    def print_config(cls):
        """Print a summary of the multi-user configuration parameters."""
        print("\n" + "=" * 70)
        print("MULTI-USER EXPERIMENT CONFIGURATION")
        print("=" * 70)
        print(f"\nExperiment: {cls.EXPERIMENT_NAME} v{cls.EXPERIMENT_VERSION}")
        print(f"Scenarios: {cls.SCENARIOS}")
        print(f"Target User m0: {cls.TARGET_M0}")
        print(f"\nData Directory: {cls.DATA_DIR}")
        print(f"SNR values: {cls.SNR_VALUES} dB (Train: {cls.TRAIN_SNR} dB)")
        print(f"Features: {cls.NUM_FEATURES}, Classes: {cls.NUM_CLASSES}")
        print(f"Split (Train/Val): {cls.TRAIN_RATIO}/{cls.VALIDATION_RATIO}")
        print("\n" + "=" * 70)


# Create global configuration instance
config_mu = ConfigMultiUser()

# =============================================================================
# Self-test when run directly
# =============================================================================
if __name__ == "__main__":
    print("\nRunning config_multiuser.py self-test...\n")

    # Validate and Print
    is_valid = config_mu.validate_config()
    if is_valid:
        config_mu.print_config()

    # Test Utility Methods
    print("\n--- Testing Utility Methods ---")
    config_mu.create_directories()

    print("\nChecking expected file paths based on MATLAB pattern:")
    files_found = 0
    files_missing = 0

    for scen in config_mu.SCENARIOS:
        filepath = config_mu.get_data_filepath(scen, config_mu.TRAIN_SNR)
        if os.path.exists(filepath):
            print(
                f"  [FOUND] Scenario '{scen}', SNR={config_mu.TRAIN_SNR}dB: {filepath}")
            files_found += 1
        else:
            print(
                f"  [MISSING] Scenario '{scen}', SNR={config_mu.TRAIN_SNR}dB: {filepath}")
            files_missing += 1

        print(f"  Model Path: {config_mu.get_model_filepath(scen)}")
        print(f"  Results Path: {config_mu.get_results_filepath(scen)}")

    print(
        f"\nSelf-test complete. Found {files_found} files, Missing {files_missing} files.")
    if files_missing > 0:
        print("NOTE: Please ensure the MATLAB files are copied to the Python directory.")
