"""
================================================================================
PUCCH Format 0 - Machine Learning Decoder
Configuration File
================================================================================

This file contains ALL configuration parameters for the experiment.
Parameters are organized into sections and documented with their sources.

Sources:
    - Paper: "Machine Learning Decoder for 5G NR PUCCH Format 0"
    - MATLAB: Our data generation code
    - Default: Reasonable defaults or common practice

================================================================================
"""

import os
import datetime


class Config:
    """
    Central configuration class containing all experiment parameters.

    Usage:
        from config import config
        print(config.TRAIN_SNR)
    """

    # =========================================================================
    # SECTION 1: EXPERIMENT IDENTIFICATION
    # =========================================================================

    # Experiment name for file naming and logging
    EXPERIMENT_NAME = "PUCCH_Format0_ML_Decoder"

    # Version tracking
    EXPERIMENT_VERSION = "1.0"

    # Timestamp (set at import time)
    EXPERIMENT_TIMESTAMP = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    # =========================================================================
    # SECTION 2: RANDOM SEEDS FOR REPRODUCIBILITY
    # =========================================================================

    # Master seed - all other seeds derived from this
    # Source: Common practice
    MASTER_SEED = 42

    # Individual seeds (can be modified for specific reproducibility needs)
    NUMPY_SEED = 42
    TENSORFLOW_SEED = 42
    SKLEARN_SEED = 42  # For train_test_split

    # =========================================================================
    # SECTION 3: DATA PARAMETERS - Must Match MATLAB Generation
    # =========================================================================

    # --- File Locations ---

    # Directory containing CSV files generated by MATLAB
    # Change this if your files are in a different location
    DATA_DIR = "./"

    # --- SNR Configuration ---
    # Source: MATLAB code - allSNRs variable

    # All SNR values for which data was generated
    SNR_VALUES = [0, 5, 10, 15, 20]  # dB

    # SNR used for training (middle value for better generalization)
    # Source: Paper - "we train the neural network on 200000 data samples
    #         generated in MATLAB at a middle SNR of 10 dB"
    TRAIN_SNR = 10  # dB

    # --- Feature Dimensions ---
    # Source: MATLAB code - 12 complex samples split into real and imaginary

    # Number of input features to neural network
    NUM_FEATURES = 24  # 12 real + 12 imaginary

    # Number of complex subcarriers per PUCCH symbol
    NUM_SUBCARRIERS = 12

    # --- Class Configuration ---
    # Source: MATLAB code - uciCombinations variable

    # Number of output classes
    NUM_CLASSES = 4

    # Class definitions - ORDER MUST MATCH MATLAB uciCombinations
    # MATLAB order:
    #   Class 0: {0, 0} = ACK=0, SR=0
    #   Class 1: {0, 1} = ACK=0, SR=1
    #   Class 2: {1, 0} = ACK=1, SR=0
    #   Class 3: {1, 1} = ACK=1, SR=1
    CLASS_LABELS = {
        0: "ACK=0, SR=0 (NACK, no SR)",
        1: "ACK=0, SR=1 (NACK, +SR)",
        2: "ACK=1, SR=0 (ACK, no SR)",
        3: "ACK=1, SR=1 (ACK, +SR)"
    }

    # Corresponding cyclic shift (mcs) values
    # Source: 3GPP specification / Paper Figure 1
    MCS_VALUES = {
        0: 0,   # Class 0 → mcs = 0
        1: 3,   # Class 1 → mcs = 3
        2: 6,   # Class 2 → mcs = 6
        3: 9    # Class 3 → mcs = 9
    }

    # --- CSV File Format ---
    # Source: MATLAB code - headerNames variable

    # Expected number of columns in CSV files
    EXPECTED_NUM_COLUMNS = 25  # 24 features + 1 label

    # Feature column names (must match MATLAB header)
    FEATURE_COLUMNS_REAL = [
        f"real_{i}" for i in range(1, 13)]  # real_1 to real_12
    FEATURE_COLUMNS_IMAG = [
        f"imag_{i}" for i in range(1, 13)]  # imag_1 to imag_12
    FEATURE_COLUMNS = FEATURE_COLUMNS_REAL + \
        FEATURE_COLUMNS_IMAG  # All 24 features

    # Label column name
    LABEL_COLUMN = "label"

    # =========================================================================
    # SECTION 4: MATLAB GENERATION PARAMETERS (For Documentation)
    # =========================================================================
    # These parameters document how the data was generated in MATLAB.
    # They are not used in Python but are important for reproducibility.

    # Number of samples per SNR value
    # Source: MATLAB code - numSamplesPerSNR
    MATLAB_SAMPLES_PER_SNR = 200000

    # Samples per class (balanced)
    MATLAB_SAMPLES_PER_CLASS = 50000  # 200000 / 4

    # Allowed slot numbers
    # Source: MATLAB code - allowedSlots, Paper - "slots 13 and 14"
    MATLAB_ALLOWED_SLOTS = [13, 14]

    # PUCCH symbol allocation
    # Source: MATLAB code - pucch.SymbolAllocation
    MATLAB_SYMBOL_START = 13
    MATLAB_SYMBOL_COUNT = 1

    # Initial cyclic shift
    # Source: MATLAB code - pucch.InitialCyclicShift, Paper - "m0 = 0"
    MATLAB_INITIAL_CYCLIC_SHIFT = 0

    # Frequency hopping
    # Source: MATLAB code - pucch.FrequencyHopping, Paper - "disabled"
    MATLAB_FREQUENCY_HOPPING = "neither"

    # Channel model
    # Source: MATLAB code - channel.DelayProfile
    MATLAB_CHANNEL_MODEL = "TDL-C"
    MATLAB_DELAY_SPREAD = 300e-9  # seconds
    MATLAB_MAX_DOPPLER = 100  # Hz

    # Carrier configuration
    # Source: MATLAB code
    MATLAB_NCELL_ID = 2
    MATLAB_SUBCARRIER_SPACING = 15  # kHz
    MATLAB_NSIZE_GRID = 25  # Resource blocks

    # Antenna configuration
    # Source: MATLAB code, Paper - "1 TX, 1 RX"
    MATLAB_NUM_TX_ANTENNAS = 1
    MATLAB_NUM_RX_ANTENNAS = 1

    # =========================================================================
    # SECTION 5: DATA SPLITTING
    # =========================================================================
    # Source: Paper - "we use 75% of the dataset for training and the
    #         remaining for testing"

    # Training ratio
    TRAIN_RATIO = 0.75

    # Validation ratio
    VALIDATION_RATIO = 0.25

    # Whether to stratify split (maintain class balance)
    # Source: Best practice
    STRATIFY_SPLIT = True

    # =========================================================================
    # SECTION 6: DATA PREPROCESSING
    # =========================================================================

    # Whether to normalize features
    # Source: Paper does NOT mention normalization
    # Setting to False to match paper exactly
    NORMALIZE_FEATURES = False

    # Normalization type (if normalization is enabled)
    # Options: "standard" (zero mean, unit variance) or "minmax" (0-1 range)
    NORMALIZATION_TYPE = "standard"

    # =========================================================================
    # SECTION 7: NEURAL NETWORK ARCHITECTURE
    # =========================================================================
    # Source: Paper - Section III.C "Neural Network Architecture"

    # Input layer size
    # Source: Paper - "an input layer size of 24 neurons"
    INPUT_SIZE = 24

    # Hidden layer configuration
    # Source: Paper - "two intermediate layers are dense layers containing
    #         128 neurons each"
    HIDDEN_LAYERS = [128, 128]

    # Hidden layer activation function
    # Source: Paper - "ReLU activation functions in the dense layers"
    HIDDEN_ACTIVATION = "relu"

    # Output layer size
    # Source: Paper - "the output neurons each represent one of four classes"
    OUTPUT_SIZE = 4

    # Output activation function
    # Source: Paper - "softmax activation function"
    OUTPUT_ACTIVATION = "softmax"

    # Dropout rate
    # Source: Paper - "we apply dropout between all the layers, with a
    #         probability of 0.5"
    DROPOUT_RATE = 0.5

    # Whether to use dropout
    USE_DROPOUT = True

    # Weight initialization
    # Source: Default Keras initialization
    KERNEL_INITIALIZER = "glorot_uniform"

    # =========================================================================
    # SECTION 8: TRAINING PARAMETERS
    # =========================================================================
    # Source: Paper - Section III.D "Training and Testing"

    # Number of training epochs
    # Source: Paper - "a training duration of 200 epochs"
    NUM_EPOCHS = 200

    # Batch size
    # Source: Not specified in paper, using common value
    BATCH_SIZE = 256

    # Optimizer
    # Source: Paper - "Stochastic Gradient Descent (SGD)"
    OPTIMIZER = "sgd"

    # Learning rate
    # Source: Paper - "a learning rate of 10^-3"
    LEARNING_RATE = 1e-3

    # SGD Momentum
    # Source: Paper - "we apply momentum which maintains an exponentially
    #         decaying moving average of prior gradients"
    MOMENTUM = 0.9

    # Nesterov momentum
    # Source: Paper does not mention Nesterov
    USE_NESTEROV = False

    # Loss function
    # Source: Paper - "Categorical Cross-Entropy loss function"
    LOSS_FUNCTION = "categorical_crossentropy"

    # =========================================================================
    # SECTION 9: TRAINING CALLBACKS
    # =========================================================================

    # --- Early Stopping ---
    # Source: Best practice (not mentioned in paper)
    USE_EARLY_STOPPING = True
    EARLY_STOPPING_MONITOR = "val_loss"
    EARLY_STOPPING_MODE = "min"
    EARLY_STOPPING_PATIENCE = 20
    EARLY_STOPPING_MIN_DELTA = 0.0001
    EARLY_STOPPING_RESTORE_BEST = True

    # --- Model Checkpoint ---
    USE_MODEL_CHECKPOINT = True
    CHECKPOINT_MONITOR = "val_accuracy"
    CHECKPOINT_MODE = "max"
    CHECKPOINT_SAVE_BEST_ONLY = True

    # --- Learning Rate Reduction ---
    USE_REDUCE_LR = True
    REDUCE_LR_MONITOR = "val_loss"
    REDUCE_LR_FACTOR = 0.5
    REDUCE_LR_PATIENCE = 10
    REDUCE_LR_MIN_LR = 1e-6

    # =========================================================================
    # SECTION 10: EXPERIMENT REPETITION
    # =========================================================================
    # For statistical significance, we can run the experiment multiple times

    # Number of times to repeat the full experiment
    # Set to 1 for single run, higher for statistical analysis
    NUM_EXPERIMENT_RUNS = 1  # Start with 1, increase for final results

    # Whether to use different random seeds for each run
    USE_DIFFERENT_SEEDS = True

    # Seed increment between runs (if USE_DIFFERENT_SEEDS is True)
    SEED_INCREMENT = 100

    # =========================================================================
    # SECTION 11: OUTPUT DIRECTORIES AND FILES
    # =========================================================================

    # Output directories
    RESULTS_DIR = "./results/"
    MODELS_DIR = "./models/"
    PLOTS_DIR = "./plots/"
    LOGS_DIR = "./logs/"

    # Output file names
    MODEL_FILENAME = "pucch_f0_nn_decoder.h5"
    SCALER_FILENAME = "feature_scaler.pkl"
    TRAINING_HISTORY_FILENAME = "training_history.csv"
    RESULTS_FILENAME = "results_summary.csv"
    DETAILED_RESULTS_FILENAME = "detailed_results.csv"
    COMPARISON_FILENAME = "nn_vs_correlation_comparison.csv"
    EXPERIMENT_LOG_FILENAME = "experiment_log.txt"

    # =========================================================================
    # SECTION 12: VISUALIZATION SETTINGS
    # =========================================================================

    # Figure sizes
    FIGURE_SIZE_SMALL = (8, 6)
    FIGURE_SIZE_MEDIUM = (10, 6)
    FIGURE_SIZE_LARGE = (12, 8)
    FIGURE_SIZE_WIDE = (14, 5)

    # Resolution for saved figures
    FIGURE_DPI = 150

    # Font sizes
    FONT_SIZE_SMALL = 10
    FONT_SIZE_MEDIUM = 12
    FONT_SIZE_LARGE = 14
    FONT_SIZE_TITLE = 16

    # =========================================================================
    # SECTION 13: UTILITY METHODS
    # =========================================================================

    @classmethod
    def create_directories(cls):
        """
        Create all output directories if they don't exist.
        Should be called at the start of the experiment.
        """
        directories = [
            cls.RESULTS_DIR,
            cls.MODELS_DIR,
            cls.PLOTS_DIR,
            cls.LOGS_DIR
        ]

        for directory in directories:
            if directory and not os.path.exists(directory):
                os.makedirs(directory)
                print(f"Created directory: {directory}")

    @classmethod
    def get_run_seed(cls, run_index: int) -> int:
        """
        Get the random seed for a specific experiment run.

        Parameters:
        -----------
        run_index : int
            Index of the run (0, 1, 2, ...)

        Returns:
        --------
        seed : int
            Random seed to use for this run
        """
        if cls.USE_DIFFERENT_SEEDS:
            return cls.MASTER_SEED + (run_index * cls.SEED_INCREMENT)
        else:
            return cls.MASTER_SEED

    @classmethod
    def get_data_filepath(cls, snr_db: int) -> str:
        """
        Get the full file path for a dataset.

        Parameters:
        -----------
        snr_db : int
            SNR value in dB

        Returns:
        --------
        filepath : str
            Full path to the CSV file
        """
        filename = f"pucch_f0_dataset_SNR_{snr_db}dB.csv"
        return os.path.join(cls.DATA_DIR, filename)

    @classmethod
    def get_model_filepath(cls, run_index: int = None) -> str:
        """
        Get the full file path for saving/loading a model.

        Parameters:
        -----------
        run_index : int, optional
            If specified, adds run index to filename

        Returns:
        --------
        filepath : str
            Full path to the model file
        """
        if run_index is not None:
            name, ext = os.path.splitext(cls.MODEL_FILENAME)
            filename = f"{name}_run{run_index}{ext}"
        else:
            filename = cls.MODEL_FILENAME

        return os.path.join(cls.MODELS_DIR, filename)

    @classmethod
    def print_config(cls):
        """
        Print a summary of all configuration parameters.
        """
        print("\n" + "=" * 70)
        print("EXPERIMENT CONFIGURATION")
        print("=" * 70)

        print(f"\n--- Experiment Info ---")
        print(f"Name: {cls.EXPERIMENT_NAME}")
        print(f"Version: {cls.EXPERIMENT_VERSION}")
        print(f"Timestamp: {cls.EXPERIMENT_TIMESTAMP}")

        print(f"\n--- Data Configuration ---")
        print(f"Data directory: {cls.DATA_DIR}")
        print(f"SNR values: {cls.SNR_VALUES} dB")
        print(f"Training SNR: {cls.TRAIN_SNR} dB")
        print(f"Number of features: {cls.NUM_FEATURES}")
        print(f"Number of classes: {cls.NUM_CLASSES}")

        print(f"\n--- Data Split ---")
        print(
            f"Train/Validation: {cls.TRAIN_RATIO:.0%}/{cls.VALIDATION_RATIO:.0%}")
        print(f"Stratified: {cls.STRATIFY_SPLIT}")

        print(f"\n--- Preprocessing ---")
        print(f"Normalize features: {cls.NORMALIZE_FEATURES}")

        print(f"\n--- Neural Network Architecture ---")
        print(f"Input: {cls.INPUT_SIZE}")
        print(f"Hidden layers: {cls.HIDDEN_LAYERS}")
        print(f"Hidden activation: {cls.HIDDEN_ACTIVATION}")
        print(f"Dropout rate: {cls.DROPOUT_RATE}")
        print(f"Output: {cls.OUTPUT_SIZE} ({cls.OUTPUT_ACTIVATION})")

        print(f"\n--- Training Parameters ---")
        print(f"Epochs: {cls.NUM_EPOCHS}")
        print(f"Batch size: {cls.BATCH_SIZE}")
        print(f"Optimizer: {cls.OPTIMIZER.upper()}")
        print(f"Learning rate: {cls.LEARNING_RATE}")
        print(f"Momentum: {cls.MOMENTUM}")

        print(f"\n--- Callbacks ---")
        print(
            f"Early stopping: {cls.USE_EARLY_STOPPING} (patience={cls.EARLY_STOPPING_PATIENCE})")
        print(f"Model checkpoint: {cls.USE_MODEL_CHECKPOINT}")
        print(f"Reduce LR: {cls.USE_REDUCE_LR}")

        print(f"\n--- Experiment Runs ---")
        print(f"Number of runs: {cls.NUM_EXPERIMENT_RUNS}")
        print(f"Random seed: {cls.MASTER_SEED}")

        print("\n" + "=" * 70)

    @classmethod
    def print_matlab_config(cls):
        """
        Print MATLAB generation parameters for reference.
        """
        print("\n" + "=" * 70)
        print("MATLAB DATA GENERATION PARAMETERS")
        print("=" * 70)

        print(f"\n--- Data Generation ---")
        print(f"Samples per SNR: {cls.MATLAB_SAMPLES_PER_SNR:,}")
        print(f"Samples per class: {cls.MATLAB_SAMPLES_PER_CLASS:,}")

        print(f"\n--- PUCCH Configuration ---")
        print(f"Allowed slots: {cls.MATLAB_ALLOWED_SLOTS}")
        print(
            f"Symbol allocation: [{cls.MATLAB_SYMBOL_START}, {cls.MATLAB_SYMBOL_COUNT}]")
        print(f"Initial cyclic shift (m0): {cls.MATLAB_INITIAL_CYCLIC_SHIFT}")
        print(f"Frequency hopping: {cls.MATLAB_FREQUENCY_HOPPING}")

        print(f"\n--- Channel Model ---")
        print(f"Channel: {cls.MATLAB_CHANNEL_MODEL}")
        print(f"Delay spread: {cls.MATLAB_DELAY_SPREAD*1e9:.0f} ns")
        print(f"Max Doppler: {cls.MATLAB_MAX_DOPPLER} Hz")

        print(f"\n--- Carrier Configuration ---")
        print(f"NCellID: {cls.MATLAB_NCELL_ID}")
        print(f"Subcarrier spacing: {cls.MATLAB_SUBCARRIER_SPACING} kHz")
        print(f"Grid size: {cls.MATLAB_NSIZE_GRID} RBs")

        print(f"\n--- Antenna Configuration ---")
        print(f"TX antennas: {cls.MATLAB_NUM_TX_ANTENNAS}")
        print(f"RX antennas: {cls.MATLAB_NUM_RX_ANTENNAS}")

        print("\n" + "=" * 70)

    @classmethod
    def validate_config(cls) -> bool:
        """
        Validate configuration parameters for consistency.

        Returns:
        --------
        is_valid : bool
            True if all parameters are valid
        """
        errors = []

        # Check SNR values
        if cls.TRAIN_SNR not in cls.SNR_VALUES:
            errors.append(
                f"TRAIN_SNR ({cls.TRAIN_SNR}) not in SNR_VALUES ({cls.SNR_VALUES})")

        # Check split ratios
        if abs(cls.TRAIN_RATIO + cls.VALIDATION_RATIO - 1.0) > 0.001:
            errors.append(f"TRAIN_RATIO + VALIDATION_RATIO should equal 1.0")

        # Check neural network dimensions
        if cls.INPUT_SIZE != cls.NUM_FEATURES:
            errors.append(
                f"INPUT_SIZE ({cls.INPUT_SIZE}) should equal NUM_FEATURES ({cls.NUM_FEATURES})")

        if cls.OUTPUT_SIZE != cls.NUM_CLASSES:
            errors.append(
                f"OUTPUT_SIZE ({cls.OUTPUT_SIZE}) should equal NUM_CLASSES ({cls.NUM_CLASSES})")

        # Check dropout rate
        if not 0.0 <= cls.DROPOUT_RATE <= 1.0:
            errors.append(
                f"DROPOUT_RATE ({cls.DROPOUT_RATE}) should be between 0 and 1")

        # Check learning rate
        if cls.LEARNING_RATE <= 0:
            errors.append(
                f"LEARNING_RATE ({cls.LEARNING_RATE}) should be positive")

        # Check class definitions
        if len(cls.CLASS_LABELS) != cls.NUM_CLASSES:
            errors.append(
                f"CLASS_LABELS has {len(cls.CLASS_LABELS)} entries, expected {cls.NUM_CLASSES}")

        if len(cls.MCS_VALUES) != cls.NUM_CLASSES:
            errors.append(
                f"MCS_VALUES has {len(cls.MCS_VALUES)} entries, expected {cls.NUM_CLASSES}")

        # Print results
        if errors:
            print("\n" + "!" * 70)
            print("CONFIGURATION VALIDATION ERRORS")
            print("!" * 70)
            for error in errors:
                print(f"  - {error}")
            print("!" * 70 + "\n")
            return False
        else:
            print("Configuration validation: PASSED")
            return True


# =============================================================================
# Create global configuration instance
# =============================================================================

config = Config()


# =============================================================================
# Self-test when run directly
# =============================================================================

if __name__ == "__main__":
    print("\nRunning config.py self-test...\n")

    # Print configurations
    config.print_config()
    config.print_matlab_config()

    # Validate
    is_valid = config.validate_config()

    # Test utility methods
    print("\n--- Testing Utility Methods ---")
    print(f"Run 0 seed: {config.get_run_seed(0)}")
    print(f"Run 1 seed: {config.get_run_seed(1)}")
    print(f"Data file for SNR=10: {config.get_data_filepath(10)}")
    print(f"Model file: {config.get_model_filepath()}")
    print(f"Model file for run 2: {config.get_model_filepath(2)}")

    # Create directories
    print("\n--- Creating Directories ---")
    config.create_directories()

    print("\n" + "=" * 70)
    print("Self-test complete!")
    print("=" * 70)
