"""
================================================================================
PUCCH Format 0 - Machine Learning Decoder
Data Loading Module
================================================================================

This module handles loading and validating CSV data files generated by MATLAB.

Functions:
    - validate_csv_file: Validate CSV file structure and content
    - load_dataset: Load a single SNR dataset
    - load_all_datasets: Load all SNR datasets
    - analyze_dataset: Analyze dataset statistics
    - reconstruct_complex: Convert real features to complex samples

================================================================================
"""

import os
import time
import numpy as np
import pandas as pd
from typing import Dict, Tuple, List, Optional

# Import configuration
from config import config


# =============================================================================
# SECTION 1: FILE VALIDATION
# =============================================================================

def validate_csv_file(
    filepath: str,
    check_all_rows: bool = False,
    verbose: bool = False
) -> Tuple[bool, str, Dict]:
    """
    Validate that a CSV file has the correct structure and content.

    This function checks:
        1. File exists and is not empty
        2. Correct number of columns (25)
        3. Correct column names (real_1...real_12, imag_1...imag_12, label)
        4. No NaN or Inf values
        5. Label values are valid (0, 1, 2, 3)
        6. Data types are correct (float for features, int for labels)

    Parameters:
    -----------
    filepath : str
        Full path to the CSV file
    check_all_rows : bool, default=False
        If True, check entire file (slower but thorough)
        If False, check only first 1000 rows (faster)
    verbose : bool, default=False
        If True, print validation details

    Returns:
    --------
    is_valid : bool
        True if file passes all validation checks
    message : str
        Description of validation result or error
    details : dict
        Dictionary containing validation details:
        - num_rows: Number of rows in file
        - num_columns: Number of columns
        - file_size_mb: File size in megabytes
        - unique_labels: Set of unique label values
        - has_nan: Whether NaN values exist
        - has_inf: Whether Inf values exist
    """

    details = {
        'num_rows': 0,
        'num_columns': 0,
        'file_size_mb': 0.0,
        'unique_labels': set(),
        'has_nan': False,
        'has_inf': False
    }

    # ----- Check 1: File exists -----
    if not os.path.exists(filepath):
        return False, f"File not found: {filepath}", details

    # ----- Check 2: File is not empty -----
    file_size = os.path.getsize(filepath)
    details['file_size_mb'] = file_size / (1024 * 1024)

    if file_size == 0:
        return False, "File is empty (0 bytes)", details

    if verbose:
        print(f"  File size: {details['file_size_mb']:.2f} MB")

    # ----- Check 3: Read and validate structure -----
    try:
        # Read file (all rows or sample)
        if check_all_rows:
            df = pd.read_csv(filepath)
        else:
            # Read first 1000 rows for quick validation
            df = pd.read_csv(filepath, nrows=1000)

        details['num_rows'] = len(df)
        details['num_columns'] = len(df.columns)

        if verbose:
            print(f"  Rows checked: {details['num_rows']}")
            print(f"  Columns: {details['num_columns']}")

    except pd.errors.EmptyDataError:
        return False, "File has no data (only header or empty)", details
    except pd.errors.ParserError as e:
        return False, f"CSV parsing error: {str(e)}", details
    except Exception as e:
        return False, f"Error reading file: {str(e)}", details

    # ----- Check 4: Number of columns -----
    expected_columns = config.EXPECTED_NUM_COLUMNS
    actual_columns = len(df.columns)

    if actual_columns != expected_columns:
        return False, f"Expected {expected_columns} columns, found {actual_columns}", details

    # ----- Check 5: Column names -----
    expected_column_names = config.FEATURE_COLUMNS + [config.LABEL_COLUMN]
    actual_column_names = list(df.columns)

    if actual_column_names != expected_column_names:
        # Find mismatches
        mismatches = []
        for i, (exp, act) in enumerate(zip(expected_column_names, actual_column_names)):
            if exp != act:
                mismatches.append(f"Column {i}: expected '{exp}', got '{act}'")

        if mismatches:
            return False, f"Column name mismatch: {mismatches[0]}", details
        else:
            return False, "Column order or names do not match expected format", details

    # ----- Check 6: NaN values -----
    nan_count = df.isnull().sum().sum()
    details['has_nan'] = nan_count > 0

    if nan_count > 0:
        nan_columns = df.columns[df.isnull().any()].tolist()
        return False, f"Found {nan_count} NaN values in columns: {nan_columns}", details

    # ----- Check 7: Feature data type (must be numeric) -----
    try:
        features = df[config.FEATURE_COLUMNS].values
        features_float = features.astype(np.float32)

        # Check for Inf values
        inf_count = np.isinf(features_float).sum()
        details['has_inf'] = inf_count > 0

        if inf_count > 0:
            return False, f"Found {inf_count} Inf values in features", details

    except (ValueError, TypeError) as e:
        return False, f"Feature columns contain non-numeric data: {str(e)}", details

    # ----- Check 8: Label values -----
    try:
        labels = df[config.LABEL_COLUMN].values
        labels_int = labels.astype(np.int32)

        unique_labels = set(labels_int)
        details['unique_labels'] = unique_labels

        valid_labels = set(range(config.NUM_CLASSES))
        invalid_labels = unique_labels - valid_labels

        if invalid_labels:
            return False, f"Invalid label values found: {invalid_labels}. Expected: {valid_labels}", details

        if verbose:
            print(f"  Unique labels: {sorted(unique_labels)}")

    except (ValueError, TypeError) as e:
        return False, f"Label column contains non-integer data: {str(e)}", details

    # ----- All checks passed -----
    return True, "File is valid", details


# =============================================================================
# SECTION 2: DATA LOADING
# =============================================================================

def load_dataset(
    snr_db: int,
    data_dir: Optional[str] = None,
    validate: bool = True,
    verbose: bool = True
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Load dataset for a single SNR value from CSV file.

    Parameters:
    -----------
    snr_db : int
        SNR value in dB (e.g., 0, 5, 10, 15, 20)
    data_dir : str, optional
        Directory containing the CSV files
        If None, uses config.DATA_DIR
    validate : bool, default=True
        If True, validate file structure before loading
    verbose : bool, default=True
        If True, print progress information

    Returns:
    --------
    X : np.ndarray
        Feature matrix of shape (num_samples, 24)
        dtype: float32
        Columns 0-11: real parts (real_1 to real_12)
        Columns 12-23: imaginary parts (imag_1 to imag_12)
    y : np.ndarray
        Label vector of shape (num_samples,)
        dtype: int32
        Values: 0, 1, 2, or 3

    Raises:
    -------
    FileNotFoundError
        If the CSV file does not exist
    ValueError
        If file validation fails

    Example:
    --------
    >>> X, y = load_dataset(snr_db=10)
    Loading pucch_f0_dataset_SNR_10dB.csv... Done! Shape: (200000, 24), Time: 2.5s
    >>> print(X.shape, y.shape)
    (200000, 24) (200000,)
    """

    # Set default data directory
    if data_dir is None:
        data_dir = config.DATA_DIR

    # Construct filename and filepath
    filename = f"pucch_f0_dataset_SNR_{snr_db}dB.csv"
    filepath = os.path.join(data_dir, filename)

    # Validate file if requested
    if validate:
        is_valid, message, details = validate_csv_file(
            filepath, check_all_rows=False, verbose=False)
        if not is_valid:
            raise ValueError(f"Invalid file '{filename}': {message}")

    # Load data
    if verbose:
        print(f"Loading {filename}...", end=" ", flush=True)

    start_time = time.time()

    # Read CSV file
    try:
        df = pd.read_csv(filepath)
    except Exception as e:
        raise RuntimeError(f"Failed to read '{filename}': {str(e)}")

    # Extract features (columns 0-23)
    X = df[config.FEATURE_COLUMNS].values.astype(np.float32)

    # Extract labels (column 24)
    y = df[config.LABEL_COLUMN].values.astype(np.int32)

    elapsed_time = time.time() - start_time

    if verbose:
        print(f"Done! Shape: {X.shape}, Time: {elapsed_time:.2f}s")

    return X, y


def load_all_datasets(
    snr_values: Optional[List[int]] = None,
    data_dir: Optional[str] = None,
    validate: bool = True,
    verbose: bool = True
) -> Dict[int, Tuple[np.ndarray, np.ndarray]]:
    """
    Load datasets for all specified SNR values.

    Parameters:
    -----------
    snr_values : list of int, optional
        List of SNR values to load
        If None, uses config.SNR_VALUES
    data_dir : str, optional
        Directory containing CSV files
        If None, uses config.DATA_DIR
    validate : bool, default=True
        If True, validate each file before loading
    verbose : bool, default=True
        If True, print progress information

    Returns:
    --------
    datasets : dict
        Dictionary mapping SNR values to (X, y) tuples
        Key: int (SNR in dB)
        Value: tuple of (X, y) where
            X: np.ndarray of shape (num_samples, 24)
            y: np.ndarray of shape (num_samples,)

    Raises:
    -------
    RuntimeError
        If no datasets could be loaded

    Example:
    --------
    >>> datasets = load_all_datasets()
    ======================================================================
    LOADING DATASETS
    ======================================================================
    Loading pucch_f0_dataset_SNR_0dB.csv... Done! Shape: (200000, 24), Time: 2.3s
    Loading pucch_f0_dataset_SNR_5dB.csv... Done! Shape: (200000, 24), Time: 2.4s
    ...
    ----------------------------------------------------------------------
    Successfully loaded: 5/5 datasets
    ======================================================================

    >>> print(datasets.keys())
    dict_keys([0, 5, 10, 15, 20])
    """

    # Set defaults
    if snr_values is None:
        snr_values = config.SNR_VALUES
    if data_dir is None:
        data_dir = config.DATA_DIR

    if verbose:
        print("\n" + "=" * 70)
        print("LOADING DATASETS")
        print("=" * 70)

    datasets = {}
    errors = []

    for snr in snr_values:
        try:
            X, y = load_dataset(
                snr_db=snr,
                data_dir=data_dir,
                validate=validate,
                verbose=verbose
            )
            datasets[snr] = (X, y)

        except FileNotFoundError as e:
            error_msg = f"File not found"
            if verbose:
                print(f"  WARNING: SNR {snr} dB - {error_msg}")
            errors.append((snr, error_msg))

        except ValueError as e:
            error_msg = str(e)
            if verbose:
                print(f"  ERROR: SNR {snr} dB - {error_msg}")
            errors.append((snr, error_msg))

        except Exception as e:
            error_msg = str(e)
            if verbose:
                print(f"  ERROR: SNR {snr} dB - {error_msg}")
            errors.append((snr, error_msg))

    if verbose:
        print("-" * 70)
        print(
            f"Successfully loaded: {len(datasets)}/{len(snr_values)} datasets")

        if errors:
            print(f"Failed to load: {len(errors)} datasets")
            for snr, msg in errors:
                print(f"  - SNR {snr} dB: {msg}")

        print("=" * 70 + "\n")

    # Check if any datasets were loaded
    if len(datasets) == 0:
        raise RuntimeError(
            f"No datasets could be loaded from '{data_dir}'. "
            f"Please check that CSV files exist and are valid."
        )

    return datasets


# =============================================================================
# SECTION 3: DATA ANALYSIS
# =============================================================================

def analyze_dataset(
    X: np.ndarray,
    y: np.ndarray,
    name: str = "Dataset",
    verbose: bool = True
) -> Dict:
    """
    Perform comprehensive analysis of a dataset.

    This function calculates:
        - Basic statistics (samples, features, dtype)
        - Feature statistics (min, max, mean, std, median)
        - Data quality metrics (NaN, Inf, zero rows)
        - Class distribution and balance

    Parameters:
    -----------
    X : np.ndarray
        Feature matrix of shape (num_samples, num_features)
    y : np.ndarray
        Label vector of shape (num_samples,)
    name : str, default="Dataset"
        Name for identification in output
    verbose : bool, default=True
        If True, print analysis results

    Returns:
    --------
    stats : dict
        Dictionary containing all statistics:
        - name: Dataset name
        - num_samples: Number of samples
        - num_features: Number of features
        - feature_dtype: Data type of features
        - label_dtype: Data type of labels
        - feature_min: Minimum feature value
        - feature_max: Maximum feature value
        - feature_mean: Mean of all features
        - feature_std: Standard deviation of all features
        - feature_median: Median of all features
        - num_nan: Number of NaN values
        - num_inf: Number of Inf values
        - num_zero_rows: Number of all-zero rows
        - class_distribution: Dict mapping class to count
        - class_percentages: Dict mapping class to percentage
        - class_balance_ratio: Max count / Min count
        - is_balanced: True if ratio < 1.1

    Example:
    --------
    >>> stats = analyze_dataset(X, y, name="Training Data")
    ============================================================
    DATASET ANALYSIS: Training Data
    ============================================================

    --- Basic Information ---
    Number of samples: 150,000
    Number of features: 24
    ...
    """

    stats = {}

    # ----- Basic information -----
    stats['name'] = name
    stats['num_samples'] = int(X.shape[0])
    stats['num_features'] = int(X.shape[1])
    stats['feature_dtype'] = str(X.dtype)
    stats['label_dtype'] = str(y.dtype)

    # ----- Feature statistics -----
    stats['feature_min'] = float(np.min(X))
    stats['feature_max'] = float(np.max(X))
    stats['feature_mean'] = float(np.mean(X))
    stats['feature_std'] = float(np.std(X))
    stats['feature_median'] = float(np.median(X))

    # Per-feature statistics
    stats['per_feature_mean'] = np.mean(X, axis=0).tolist()
    stats['per_feature_std'] = np.std(X, axis=0).tolist()

    # ----- Data quality -----
    stats['num_nan'] = int(np.sum(np.isnan(X)))
    stats['num_inf'] = int(np.sum(np.isinf(X)))
    stats['num_zero_rows'] = int(np.sum(np.all(X == 0, axis=1)))

    # ----- Class distribution -----
    unique_labels, counts = np.unique(y, return_counts=True)

    stats['class_distribution'] = {
        int(label): int(count)
        for label, count in zip(unique_labels, counts)
    }

    stats['class_percentages'] = {
        int(label): float(count / len(y) * 100)
        for label, count in zip(unique_labels, counts)
    }

    # Class balance
    if len(counts) > 0 and min(counts) > 0:
        stats['class_balance_ratio'] = float(max(counts) / min(counts))
    else:
        stats['class_balance_ratio'] = float('inf')

    stats['is_balanced'] = stats['class_balance_ratio'] < 1.1

    # ----- Print results -----
    if verbose:
        print(f"\n{'='*60}")
        print(f"DATASET ANALYSIS: {name}")
        print(f"{'='*60}")

        print(f"\n--- Basic Information ---")
        print(f"Number of samples: {stats['num_samples']:,}")
        print(f"Number of features: {stats['num_features']}")
        print(f"Feature dtype: {stats['feature_dtype']}")
        print(f"Label dtype: {stats['label_dtype']}")

        print(f"\n--- Feature Statistics ---")
        print(f"Min: {stats['feature_min']:.6f}")
        print(f"Max: {stats['feature_max']:.6f}")
        print(f"Mean: {stats['feature_mean']:.6f}")
        print(f"Std: {stats['feature_std']:.6f}")
        print(f"Median: {stats['feature_median']:.6f}")

        print(f"\n--- Data Quality ---")
        print(f"NaN values: {stats['num_nan']}")
        print(f"Inf values: {stats['num_inf']}")
        print(f"All-zero rows: {stats['num_zero_rows']}")

        print(f"\n--- Class Distribution ---")
        for label in sorted(stats['class_distribution'].keys()):
            count = stats['class_distribution'][label]
            pct = stats['class_percentages'][label]
            class_name = config.CLASS_LABELS.get(label, f"Class {label}")
            print(
                f"  Class {label}: {count:,} samples ({pct:.2f}%) - {class_name}")

        print(f"\nClass balance ratio: {stats['class_balance_ratio']:.4f}")
        balance_status = "YES" if stats['is_balanced'] else "NO"
        print(f"Is balanced (within 10%): {balance_status}")

        print(f"{'='*60}\n")

    return stats


# =============================================================================
# SECTION 4: DATA TRANSFORMATION
# =============================================================================

def reconstruct_complex(X: np.ndarray) -> np.ndarray:
    """
    Reconstruct complex samples from real-valued feature matrix.

    The feature matrix format is:
        [real_1, real_2, ..., real_12, imag_1, imag_2, ..., imag_12]

    This function combines them into complex numbers:
        complex_i = real_i + j * imag_i

    Parameters:
    -----------
    X : np.ndarray
        Feature matrix of shape (num_samples, 24)
        Columns 0-11: real parts
        Columns 12-23: imaginary parts

    Returns:
    --------
    X_complex : np.ndarray
        Complex array of shape (num_samples, 12)
        dtype: complex64

    Raises:
    -------
    ValueError
        If X does not have exactly 24 columns

    Example:
    --------
    >>> X = np.random.randn(100, 24).astype(np.float32)
    >>> X_complex = reconstruct_complex(X)
    >>> print(X_complex.shape, X_complex.dtype)
    (100, 12) complex64
    """

    # Validate input
    if X.ndim != 2:
        raise ValueError(f"Expected 2D array, got {X.ndim}D")

    if X.shape[1] != 24:
        raise ValueError(f"Expected 24 columns, got {X.shape[1]}")

    # Extract real and imaginary parts
    real_parts = X[:, :12]   # Columns 0-11
    imag_parts = X[:, 12:]   # Columns 12-23

    # Combine into complex numbers
    X_complex = (real_parts + 1j * imag_parts).astype(np.complex64)

    return X_complex


def split_complex_to_real(X_complex: np.ndarray) -> np.ndarray:
    """
    Split complex samples into real-valued feature matrix.

    This is the inverse of reconstruct_complex().

    Parameters:
    -----------
    X_complex : np.ndarray
        Complex array of shape (num_samples, 12)

    Returns:
    --------
    X : np.ndarray
        Feature matrix of shape (num_samples, 24)
        Columns 0-11: real parts
        Columns 12-23: imaginary parts
        dtype: float32

    Raises:
    -------
    ValueError
        If X_complex does not have exactly 12 columns

    Example:
    --------
    >>> X_complex = np.random.randn(100, 12) + 1j * np.random.randn(100, 12)
    >>> X = split_complex_to_real(X_complex.astype(np.complex64))
    >>> print(X.shape, X.dtype)
    (100, 24) float32
    """

    # Validate input
    if X_complex.ndim != 2:
        raise ValueError(f"Expected 2D array, got {X_complex.ndim}D")

    if X_complex.shape[1] != 12:
        raise ValueError(f"Expected 12 columns, got {X_complex.shape[1]}")

    # Extract real and imaginary parts
    real_parts = np.real(X_complex)
    imag_parts = np.imag(X_complex)

    # Concatenate
    X = np.concatenate([real_parts, imag_parts], axis=1).astype(np.float32)

    return X


# =============================================================================
# SECTION 5: SELF-TEST
# =============================================================================

if __name__ == "__main__":
    """
    Self-test for data_loader module.
    Run this file directly to test all functions.
    """

    print("\n" + "=" * 70)
    print("DATA LOADER MODULE - SELF TEST")
    print("=" * 70)

    # Test 1: Check if data files exist
    print("\n--- Test 1: Checking for data files ---")

    files_found = 0
    files_missing = 0

    for snr in config.SNR_VALUES:
        filepath = config.get_data_filepath(snr)
        if os.path.exists(filepath):
            files_found += 1
            print(f"  [FOUND] SNR {snr} dB: {filepath}")
        else:
            files_missing += 1
            print(f"  [MISSING] SNR {snr} dB: {filepath}")

    print(f"\nFound: {files_found}, Missing: {files_missing}")

    if files_found == 0:
        print("\nNo data files found. Skipping remaining tests.")
        print("Please run MATLAB code first to generate CSV files.")
        print("=" * 70)
        exit()

    # Test 2: Validate a file
    print("\n--- Test 2: File validation ---")

    # Find first available SNR
    test_snr = None
    for snr in config.SNR_VALUES:
        filepath = config.get_data_filepath(snr)
        if os.path.exists(filepath):
            test_snr = snr
            break

    if test_snr is not None:
        filepath = config.get_data_filepath(test_snr)
        print(f"Validating: {filepath}")

        is_valid, message, details = validate_csv_file(
            filepath, check_all_rows=False, verbose=True)

        print(f"Valid: {is_valid}")
        print(f"Message: {message}")
        print(f"Details: {details}")

    # Test 3: Load a dataset
    print("\n--- Test 3: Load single dataset ---")

    if test_snr is not None:
        try:
            X, y = load_dataset(snr_db=test_snr, validate=True, verbose=True)
            print(f"X shape: {X.shape}, dtype: {X.dtype}")
            print(f"y shape: {y.shape}, dtype: {y.dtype}")
            print(f"X sample: {X[0, :5]}...")
            print(f"y sample: {y[:10]}")
        except Exception as e:
            print(f"Error: {e}")

    # Test 4: Analyze dataset
    print("\n--- Test 4: Analyze dataset ---")

    if test_snr is not None:
        try:
            X, y = load_dataset(snr_db=test_snr, verbose=False)
            stats = analyze_dataset(X, y, name=f"SNR {test_snr} dB")
        except Exception as e:
            print(f"Error: {e}")

    # Test 5: Complex reconstruction
    print("\n--- Test 5: Complex reconstruction ---")

    # Create test data
    test_X = np.random.randn(10, 24).astype(np.float32)
    print(f"Original shape: {test_X.shape}")

    # Convert to complex
    X_complex = reconstruct_complex(test_X)
    print(f"Complex shape: {X_complex.shape}, dtype: {X_complex.dtype}")

    # Convert back to real
    X_recovered = split_complex_to_real(X_complex)
    print(f"Recovered shape: {X_recovered.shape}, dtype: {X_recovered.dtype}")

    # Check if recovery is exact
    max_error = np.max(np.abs(test_X - X_recovered))
    print(f"Max reconstruction error: {max_error}")

    if max_error < 1e-6:
        print("Reconstruction: PASS")
    else:
        print("Reconstruction: FAIL")

    # Test 6: Load all datasets
    print("\n--- Test 6: Load all datasets ---")

    try:
        datasets = load_all_datasets(validate=True, verbose=True)
        print(f"Loaded SNR values: {list(datasets.keys())}")
    except Exception as e:
        print(f"Error: {e}")

    print("\n" + "=" * 70)
    print("SELF TEST COMPLETE")
    print("=" * 70)
