"""
PUCCH Format 0 - Multi-User Machine Learning Decoder
Data Loading Module

This module handles loading and validating CSV data files generated by MATLAB
for Multi-User PUCCH Format 0 scenarios.

Functions:
    - validate_multi_ue_csv: Validate CSV file structure and content
    - load_multi_ue_dataset: Load a single SNR dataset for a specific scenario
    - load_all_multi_ue_datasets: Load all SNR datasets for a scenario
    - analyze_multi_ue_dataset: Analyze dataset statistics
    - reconstruct_complex: Convert real features to complex samples

Usage:
    from data_loader_multi_ue import load_all_multi_ue_datasets
    datasets = load_all_multi_ue_datasets(scenario="2users")
================================================================================
"""
import os
import time
import numpy as np
import pandas as pd
from typing import Dict, Tuple, List, Optional

# Import configuration
from config_multi_ue import config_multi_ue


# =============================================================================
# SECTION 1: FILE VALIDATION
# =============================================================================

def validate_multi_ue_csv(
    filepath: str,
    check_all_rows: bool = False,
    verbose: bool = False
) -> Tuple[bool, str, Dict]:
    """
    Validate that a Multi-User CSV file has the correct structure and content.

    This function checks:
        1. File exists and is not empty
        2. Correct number of columns (25)
        3. Correct column names (real_1...real_12, imag_1...imag_12, label)
        4. No NaN or Inf values
        5. Label values are valid (0, 1, 2, 3)
        6. Data types are correct

    Parameters:
    -----------
    filepath : str
        Full path to the CSV file
    check_all_rows : bool, default=False
        If True, check entire file (slower but thorough)
    verbose : bool, default=False
        If True, print validation details

    Returns:
    --------
    is_valid : bool
        True if file passes all validation checks
    message : str
        Description of validation result or error
    details : dict
        Dictionary containing validation details
    """

    details = {
        'num_rows': 0,
        'num_columns': 0,
        'file_size_mb': 0.0,
        'unique_labels': set(),
        'has_nan': False,
        'has_inf': False
    }

    # ----- Check 1: File exists -----
    if not os.path.exists(filepath):
        return False, f"File not found: {filepath}", details

    # ----- Check 2: File is not empty -----
    file_size = os.path.getsize(filepath)
    details['file_size_mb'] = file_size / (1024 * 1024)

    if file_size == 0:
        return False, "File is empty (0 bytes)", details

    if verbose:
        print(f"  File size: {details['file_size_mb']:.2f} MB")

    # ----- Check 3: Read and validate structure -----
    try:
        if check_all_rows:
            df = pd.read_csv(filepath)
        else:
            # Read first 1000 rows for quick validation
            df = pd.read_csv(filepath, nrows=1000)

        details['num_rows'] = len(df)
        details['num_columns'] = len(df.columns)

        if verbose:
            print(f"  Rows checked: {details['num_rows']}")
            print(f"  Columns: {details['num_columns']}")

    except pd.errors.EmptyDataError:
        return False, "File has no data (only header or empty)", details
    except pd.errors.ParserError as e:
        return False, f"CSV parsing error: {str(e)}", details
    except Exception as e:
        return False, f"Error reading file: {str(e)}", details

    # ----- Check 4: Number of columns -----
    expected_columns = config_multi_ue.EXPECTED_NUM_COLUMNS
    actual_columns = len(df.columns)

    if actual_columns != expected_columns:
        return False, f"Expected {expected_columns} columns, found {actual_columns}", details

    # ----- Check 5: Column names -----
    expected_column_names = config_multi_ue.FEATURE_COLUMNS + \
        [config_multi_ue.LABEL_COLUMN]
    actual_column_names = list(df.columns)

    if actual_column_names != expected_column_names:
        mismatches = []
        for i, (exp, act) in enumerate(zip(expected_column_names, actual_column_names)):
            if exp != act:
                mismatches.append(f"Column {i}: expected '{exp}', got '{act}'")

        if mismatches:
            return False, f"Column name mismatch: {mismatches[0]}", details
        else:
            return False, "Column order or names do not match expected format", details

    # ----- Check 6: NaN values -----
    nan_count = df.isnull().sum().sum()
    details['has_nan'] = nan_count > 0

    if nan_count > 0:
        nan_columns = df.columns[df.isnull().any()].tolist()
        return False, f"Found {nan_count} NaN values in columns: {nan_columns}", details

    # ----- Check 7: Feature data type (must be numeric) -----
    try:
        features = df[config_multi_ue.FEATURE_COLUMNS].values
        features_float = features.astype(np.float32)

        # Check for Inf values
        inf_count = np.isinf(features_float).sum()
        details['has_inf'] = inf_count > 0

        if inf_count > 0:
            return False, f"Found {inf_count} Inf values in features", details

    except (ValueError, TypeError) as e:
        return False, f"Feature columns contain non-numeric data: {str(e)}", details

    # ----- Check 8: Label values -----
    try:
        labels = df[config_multi_ue.LABEL_COLUMN].values
        labels_int = labels.astype(np.int32)

        unique_labels = set(labels_int)
        details['unique_labels'] = unique_labels

        valid_labels = set(range(config_multi_ue.NUM_CLASSES))
        invalid_labels = unique_labels - valid_labels

        if invalid_labels:
            return False, f"Invalid label values found: {invalid_labels}. Expected: {valid_labels}", details

        if verbose:
            print(f"  Unique labels: {sorted(unique_labels)}")

    except (ValueError, TypeError) as e:
        return False, f"Label column contains non-integer data: {str(e)}", details

    # ----- All checks passed -----
    return True, "File is valid", details


# =============================================================================
# SECTION 2: DATA LOADING
# =============================================================================

def load_multi_ue_dataset(
    snr_db: int,
    scenario: Optional[str] = None,
    data_dir: Optional[str] = None,
    validate: bool = True,
    verbose: bool = True
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Load Multi-User dataset for a single SNR value from CSV file.

    Parameters:
    -----------
    snr_db : int
        SNR value in dB (e.g., 0, 5, 10, 15, 20)
    scenario : str, optional
        Scenario name ("2users" or "3users")
        If None, uses config_multi_ue.CURRENT_SCENARIO_KEY
    data_dir : str, optional
        Directory containing the CSV files
        If None, uses config_multi_ue.DATA_DIR
    validate : bool, default=True
        If True, validate file structure before loading
    verbose : bool, default=True
        If True, print progress information

    Returns:
    --------
    X : np.ndarray
        Feature matrix of shape (num_samples, 24)
        dtype: float32
    y : np.ndarray
        Label vector of shape (num_samples,)
        dtype: int32
        Values: 0, 1, 2, or 3 (Target User UCI only)

    Raises:
    -------
    FileNotFoundError
        If the CSV file does not exist
    ValueError
        If file validation fails
    """

    # Set defaults
    if scenario is None:
        scenario = config_multi_ue.CURRENT_SCENARIO_KEY
    if data_dir is None:
        data_dir = config_multi_ue.DATA_DIR

    # Construct filename and filepath
    filename = f"pucch_f0_{scenario}_SNR_{snr_db}dB.csv"
    filepath = os.path.join(data_dir, filename)

    # Validate file if requested
    if validate:
        is_valid, message, details = validate_multi_ue_csv(
            filepath, check_all_rows=False, verbose=False)
        if not is_valid:
            raise ValueError(f"Invalid file '{filename}': {message}")

    # Load data
    if verbose:
        print(f"Loading {filename}... ", end="", flush=True)

    start_time = time.time()

    # Read CSV file
    try:
        df = pd.read_csv(filepath)
    except Exception as e:
        raise RuntimeError(f"Failed to read '{filename}': {str(e)}")

    # Extract features (columns 0-23)
    X = df[config_multi_ue.FEATURE_COLUMNS].values.astype(np.float32)

    # Extract labels (column 24)
    y = df[config_multi_ue.LABEL_COLUMN].values.astype(np.int32)

    elapsed_time = time.time() - start_time

    if verbose:
        print(f"Done! Shape: {X.shape}, Time: {elapsed_time:.2f}s")

    return X, y


def load_all_multi_ue_datasets(
    snr_values: Optional[List[int]] = None,
    scenario: Optional[str] = None,
    data_dir: Optional[str] = None,
    validate: bool = True,
    verbose: bool = True
) -> Dict[int, Tuple[np.ndarray, np.ndarray]]:
    """
    Load Multi-User datasets for all specified SNR values.

    Parameters:
    -----------
    snr_values : list of int, optional
        List of SNR values to load
        If None, uses config_multi_ue.SNR_VALUES
    scenario : str, optional
        Scenario name ("2users" or "3users")
        If None, uses config_multi_ue.CURRENT_SCENARIO_KEY
    data_dir : str, optional
        Directory containing CSV files
        If None, uses config_multi_ue.DATA_DIR
    validate : bool, default=True
        If True, validate each file before loading
    verbose : bool, default=True
        If True, print progress information

    Returns:
    --------
    datasets : dict
        Dictionary mapping SNR values to (X, y) tuples
        Key: int (SNR in dB)
        Value: tuple of (X, y)

    Raises:
    -------
    RuntimeError
        If no datasets could be loaded
    """

    # Set defaults
    if snr_values is None:
        snr_values = config_multi_ue.SNR_VALUES
    if scenario is None:
        scenario = config_multi_ue.CURRENT_SCENARIO_KEY
    if data_dir is None:
        data_dir = config_multi_ue.DATA_DIR

    if verbose:
        print("\n" + "=" * 70)
        print("LOADING MULTI-USER DATASETS")
        print("=" * 70)
        print(f"Scenario: {scenario}")
        print(f"Data directory: {data_dir}")
        print(f"SNR values: {snr_values}")
        print("=" * 70)

    datasets = {}
    errors = []

    for snr in snr_values:
        try:
            X, y = load_multi_ue_dataset(
                snr_db=snr,
                scenario=scenario,
                data_dir=data_dir,
                validate=validate,
                verbose=verbose
            )
            datasets[snr] = (X, y)

        except FileNotFoundError as e:
            error_msg = "File not found"
            if verbose:
                print(f"  WARNING: SNR {snr} dB - {error_msg}")
            errors.append((snr, error_msg))

        except ValueError as e:
            error_msg = str(e)
            if verbose:
                print(f"  ERROR: SNR {snr} dB - {error_msg}")
            errors.append((snr, error_msg))

        except Exception as e:
            error_msg = str(e)
            if verbose:
                print(f"  ERROR: SNR {snr} dB - {error_msg}")
            errors.append((snr, error_msg))

    if verbose:
        print("-" * 70)
        print(
            f"Successfully loaded: {len(datasets)}/{len(snr_values)} datasets")

        if errors:
            print(f"Failed to load: {len(errors)} datasets")
            for snr, msg in errors:
                print(f"  - SNR {snr} dB: {msg}")

        print("=" * 70 + "\n")

    # Check if any datasets were loaded
    if len(datasets) == 0:
        raise RuntimeError(
            f"No datasets could be loaded from '{data_dir}'. "
            f"Please check that CSV files exist and are valid."
        )

    return datasets


# =============================================================================
# SECTION 3: DATA ANALYSIS
# =============================================================================

def analyze_multi_ue_dataset(
    X: np.ndarray,
    y: np.ndarray,
    scenario: str,
    name: str = "Multi-User Dataset",
    verbose: bool = True
) -> Dict:
    """
    Perform comprehensive analysis of a Multi-User dataset.

    Parameters:
    -----------
    X : np.ndarray
        Feature matrix of shape (num_samples, num_features)
    y : np.ndarray
        Label vector of shape (num_samples,)
    scenario : str
        Scenario name ("2users" or "3users")
    name : str, default="Multi-User Dataset"
        Name for identification in output
    verbose : bool, default=True
        If True, print analysis results

    Returns:
    --------
    stats : dict
        Dictionary containing all statistics
    """

    stats = {}

    # ----- Basic information -----
    stats['name'] = name
    stats['scenario'] = scenario
    stats['num_samples'] = int(X.shape[0])
    stats['num_features'] = int(X.shape[1])
    stats['feature_dtype'] = str(X.dtype)
    stats['label_dtype'] = str(y.dtype)

    # ----- Feature statistics -----
    stats['feature_min'] = float(np.min(X))
    stats['feature_max'] = float(np.max(X))
    stats['feature_mean'] = float(np.mean(X))
    stats['feature_std'] = float(np.std(X))
    stats['feature_median'] = float(np.median(X))

    # ----- Data quality -----
    stats['num_nan'] = int(np.sum(np.isnan(X)))
    stats['num_inf'] = int(np.sum(np.isinf(X)))
    stats['num_zero_rows'] = int(np.sum(np.all(X == 0, axis=1)))

    # ----- Class distribution -----
    unique_labels, counts = np.unique(y, return_counts=True)

    stats['class_distribution'] = {
        int(label): int(count)
        for label, count in zip(unique_labels, counts)
    }

    stats['class_percentages'] = {
        int(label): float(count / len(y) * 100)
        for label, count in zip(unique_labels, counts)
    }

    # Class balance
    if len(counts) > 0 and min(counts) > 0:
        stats['class_balance_ratio'] = float(max(counts) / min(counts))
    else:
        stats['class_balance_ratio'] = float('inf')

    stats['is_balanced'] = stats['class_balance_ratio'] < 1.1

    # ----- Print results -----
    if verbose:
        print(f"\n{'='*60}")
        print(f"DATASET ANALYSIS: {name}")
        print(f"Scenario: {scenario}")
        print(f"{'='*60}")

        print(f"\n--- Basic Information ---")
        print(f"Number of samples: {stats['num_samples']:,}")
        print(f"Number of features: {stats['num_features']}")
        print(f"Feature dtype: {stats['feature_dtype']}")
        print(f"Label dtype: {stats['label_dtype']}")

        print(f"\n--- Feature Statistics ---")
        print(f"Min: {stats['feature_min']:.6f}")
        print(f"Max: {stats['feature_max']:.6f}")
        print(f"Mean: {stats['feature_mean']:.6f}")
        print(f"Std: {stats['feature_std']:.6f}")
        print(f"Median: {stats['feature_median']:.6f}")

        print(f"\n--- Data Quality ---")
        print(f"NaN values: {stats['num_nan']}")
        print(f"Inf values: {stats['num_inf']}")
        print(f"All-zero rows: {stats['num_zero_rows']}")

        print(f"\n--- Class Distribution ---")
        for label in sorted(stats['class_distribution'].keys()):
            count = stats['class_distribution'][label]
            pct = stats['class_percentages'][label]
            class_name = config_multi_ue.CLASS_LABELS.get(
                label, f"Class {label}")
            print(
                f"  Class {label}: {count:,} samples ({pct:.2f}%) - {class_name}")

        print(f"\nClass balance ratio: {stats['class_balance_ratio']:.4f}")
        balance_status = "YES" if stats['is_balanced'] else "NO"
        print(f"Is balanced (within 10%): {balance_status}")

        print(f"{'='*60}\n")

    return stats


# =============================================================================
# SECTION 4: DATA TRANSFORMATION
# =============================================================================

def reconstruct_complex(X: np.ndarray) -> np.ndarray:
    """
    Reconstruct complex samples from real-valued feature matrix.

    The feature matrix format is:
        [real_1, real_2, ..., real_12, imag_1, imag_2, ..., imag_12]

    This function combines them into complex numbers:
        complex_i = real_i + j * imag_i

    Parameters:
    -----------
    X : np.ndarray
        Feature matrix of shape (num_samples, 24)

    Returns:
    --------
    X_complex : np.ndarray
        Complex array of shape (num_samples, 12)
        dtype: complex64
    """

    if X.ndim != 2:
        raise ValueError(f"Expected 2D array, got {X.ndim}D")

    if X.shape[1] != 24:
        raise ValueError(f"Expected 24 columns, got {X.shape[1]}")

    # Extract real and imaginary parts
    real_parts = X[:, :12]   # Columns 0-11
    imag_parts = X[:, 12:]   # Columns 12-23

    # Combine into complex numbers
    X_complex = (real_parts + 1j * imag_parts).astype(np.complex64)

    return X_complex


def split_complex_to_real(X_complex: np.ndarray) -> np.ndarray:
    """
    Split complex samples into real-valued feature matrix.

    Parameters:
    -----------
    X_complex : np.ndarray
        Complex array of shape (num_samples, 12)

    Returns:
    --------
    X : np.ndarray
        Feature matrix of shape (num_samples, 24)
        dtype: float32
    """

    if X_complex.ndim != 2:
        raise ValueError(f"Expected 2D array, got {X_complex.ndim}D")

    if X_complex.shape[1] != 12:
        raise ValueError(f"Expected 12 columns, got {X_complex.shape[1]}")

    # Extract real and imaginary parts
    real_parts = np.real(X_complex)
    imag_parts = np.imag(X_complex)

    # Concatenate
    X = np.concatenate([real_parts, imag_parts], axis=1).astype(np.float32)

    return X


# =============================================================================
# SECTION 5: SELF-TEST
# =============================================================================

if __name__ == "__main__":
    """
    Self-test for data_loader_multi_ue module.
    """
    print("\n" + "=" * 70)
    print("MULTI-USER DATA LOADER MODULE - SELF TEST")
    print("=" * 70)

    # Test 1: Check if data files exist
    print("\n--- Test 1: Checking for Multi-User data files ---")

    files_found = 0
    files_missing = 0

    for snr in config_multi_ue.SNR_VALUES:
        filepath = config_multi_ue.get_data_filepath(snr)
        if os.path.exists(filepath):
            files_found += 1
            print(f"  [FOUND] SNR {snr} dB: {filepath}")
        else:
            files_missing += 1
            print(f"  [MISSING] SNR {snr} dB: {filepath}")

    print(f"\nFound: {files_found}, Missing: {files_missing}")

    if files_found == 0:
        print("\nNo Multi-User data files found.")
        print("Please run MATLAB code first to generate CSV files.")
        print(f"Expected directory: {config_multi_ue.DATA_DIR}")
        print("=" * 70)
    else:
        # Test 2: Validate a file
        print("\n--- Test 2: File validation ---")

        test_snr = None
        for snr in config_multi_ue.SNR_VALUES:
            filepath = config_multi_ue.get_data_filepath(snr)
            if os.path.exists(filepath):
                test_snr = snr
                break

        if test_snr is not None:
            filepath = config_multi_ue.get_data_filepath(test_snr)
            print(f"Validating: {filepath}")

            is_valid, message, details = validate_multi_ue_csv(
                filepath, check_all_rows=False, verbose=True)

            print(f"Valid: {is_valid}")
            print(f"Message: {message}")

        # Test 3: Load a dataset
        print("\n--- Test 3: Load single Multi-User dataset ---")

        if test_snr is not None:
            try:
                X, y = load_multi_ue_dataset(
                    snr_db=test_snr, validate=True, verbose=True)
                print(f"X shape: {X.shape}, dtype: {X.dtype}")
                print(f"y shape: {y.shape}, dtype: {y.dtype}")
                print(f"X sample: {X[0, :5]}...")
                print(f"y sample: {y[:10]}")
                print("Test 3: PASS")
            except Exception as e:
                print(f"Test 3: FAIL - {e}")

        # Test 4: Analyze dataset
        print("\n--- Test 4: Analyze Multi-User dataset ---")

        if test_snr is not None:
            try:
                X, y = load_multi_ue_dataset(snr_db=test_snr, verbose=False)
                stats = analyze_multi_ue_dataset(
                    X, y,
                    scenario=config_multi_ue.CURRENT_SCENARIO_KEY,
                    name=f"SNR {test_snr} dB",
                    verbose=True)
                print("Test 4: PASS")
            except Exception as e:
                print(f"Test 4: FAIL - {e}")

        # Test 5: Load all datasets
        print("\n--- Test 5: Load all Multi-User datasets ---")

        try:
            datasets = load_all_multi_ue_datasets(validate=True, verbose=True)
            print(f"Loaded SNR values: {list(datasets.keys())}")
            print("Test 5: PASS")
        except Exception as e:
            print(f"Test 5: FAIL - {e}")

        # Test 6: Complex reconstruction
        print("\n--- Test 6: Complex reconstruction ---")

        test_X = np.random.randn(10, 24).astype(np.float32)
        print(f"Original shape: {test_X.shape}")

        X_complex = reconstruct_complex(test_X)
        print(f"Complex shape: {X_complex.shape}, dtype: {X_complex.dtype}")

        X_recovered = split_complex_to_real(X_complex)
        print(
            f"Recovered shape: {X_recovered.shape}, dtype: {X_recovered.dtype}")

        max_error = np.max(np.abs(test_X - X_recovered))
        print(f"Max reconstruction error: {max_error}")

        if max_error < 1e-6:
            print("Reconstruction: PASS")
        else:
            print("Reconstruction: FAIL")

    print("\n" + "=" * 70)
    print("SELF TEST COMPLETE")
    print("=" * 70)
